version: '3.8'

services:

  # Next.js Application
  glumia-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: glumia-app
    restart: unless-stopped
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SITE_URL=https://glumia.com
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_FROM=${SMTP_FROM}
      - SMTP_TO=${SMTP_TO}
      - SMTP_SUBSCRIPTION_BOX=${SMTP_SUBSCRIPTION_BOX}
    ports:
      - "3002:3000"
    networks:
      - glumia-network

networks:
  glumia-network:
    driver: bridge
